Upgrade to cordova ios 6.1.1
forcedotcom/SalesforceMobileSDK-iOS-Hybrid pull request #155
Opened 2020-10-27 21:34 UTC by wmathurin

We no longer need the cordova wkwebview engine plugin.

2020-10-27 21:40 UTC, bhariharan approved these changes
@wmathurin Did you verify that all the PRs I had made on our fork made it upstream? Some of them may not apply anymore, since `6.1.1` has removed all `UIWebView` references. I had made a few project file tweaks to work with our internal projects too, but I can verify those by upgrading the `Community Container` to use this and try it.

2020-10-27 21:43 UTC, wmathurin commented
According to your comment [here](https://github.com/forcedotcom/cordova-ios/pull/31#issuecomment-583514169), we shouldn't need the fork anymore.

2020-10-27 22:00 UTC, bhariharan approved these changes

2020-10-27 23:13 UTC, bhariharan approved these changes

2020-10-27 23:36 UTC, bhariharan approved these changes

2020-10-27 23:37 UTC, wmathurin commented
Not merging quite yet, having issues with the sample apps and the tests.

2020-10-28 22:49 UTC, bhariharan requested changes

2020-10-28 22:49 UTC, bhariharan commented on .gitmodules
> +	url = https://github.com/wmathurin/cordova-ios
Should be `forcedotcom`.

2020-10-28 23:34 UTC, wmathurin commented on .gitmodules
> -[submodule "external/cordova-ios/cordova-ios"]
Not sure why we had it nested.

2020-10-28 23:35 UTC, wmathurin commented on hybrid/SampleApps/AccountEditor/AccountEditor.xcodeproj/project.pbxproj
> -				CED7471C1E8C82150019AA9D /* CDVWKProcessPoolFactory.h */,
WKWebViewEngine is gone.

2020-10-28 23:37 UTC, wmathurin commented on shared/hybrid/cordova_plugins.js
> -    "com.salesforce": "7.2.0",
NB That version does not really matter (it's not touched by the setVersion.sh script currently).

2020-10-28 23:38 UTC, wmathurin commented on hybrid/SampleApps/AccountEditor/AccountEditor.xcodeproj/project.pbxproj
> -				B7BAD75D1FBB7DEE0046629F /* IDPLoginNavViewController.h */,
These classes don't exist since https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3102

2020-10-28 23:38 UTC, bhariharan reviewed
Don't we need the deleted files under `shared/hybrid` anymore? Also, you need to update the symlinks to `cordova.js`, since the submodule path changed.

2020-10-28 23:41 UTC, wmathurin commented
@bhariharan I fixed all the project files.
For instance, cordova.js comes from ../../../external/cordova-ios/CordovaLib/cordova.js

2020-10-28 23:44 UTC, bhariharan approved these changes

2020-10-29 00:08 UTC, merged